/* --------     Infrmc´  cm se recibe d un Servidor   -------------------------------------------- */
let estudiantes_Funval = [
  { nombre: "Alfredo",
    pais: "Mexico",
    edad: 20,           
    nota: 75,            },
  { nombre: "Belen",
    pais: "Bolivia",
    edad: 20,
    nota: 70,            },    
  { nombre: "Boren",
    pais: "Colombia",
    edad: 21,
    nota: 80            },    
  { nombre: "David",
    pais: "Chile",
    edad: 22,
    nota: 90            },    
  { nombre: "Ibraim",
    pais: "Mexico",
    edad: 23,
    nota: 95,            },    
  { nombre: "Moises",
    pais: "Bolivia",
    edad: 24,
    nota: 96            },    
  { nombre: "Gerardo",
    pais: "El Salvador",
    edad: 25,
    nota: 96            },
  { nombre: "Jorge",
    pais: "Perú",
    edad: 25,
    nota: 96            },        
];